var _lang = {
    lang_name: "English",
    login_title: "Login",
    login_user_name: "User name:",
    login_password: "Password:",
    login_button: "Log in",
    register_title: "Register user",
    register_login: "User name:",
    register_password: "Password:",
    register_name: "First name:",
    register_surname: "Last name:",
    register_id: "DNI:",
    register_email: "Email:",
    register_button: "Register",
    user_title: "Users",
    user_login: "User",
    user_name: "First Name",
    user_surname: "Last Name",
    user_email: "Email",
    user_add_button: "Add",
    modify_button: "Edit",
    user_add_title: "Add user",
    user_add_login: "Login:",
    user_add_password: "Password:",
    user_add_id: "DNI:",
    user_add_submit: "Send",
    user_edit_title: "Edit user",
    user_edit_submit: "Modify",
    entrega_add_title: "Add task",
    entrega_id: "Id:",
    entrega_name: "Name:",
    entrega_from: "From:",
    entrega_to: "To:",
    entrega_to_corr: "Grading to:",
    entrega_l_to_corr: "Grade to:",
    entrega_add_submit: "Add",
    entrega_list_title: "Task list",
    entrega_l_id: "Id",
    entrega_l_name: "Name",
    entrega_l_from: "From",
    entrega_l_to: "To",
    entrega_l_add: "Add task",
    entrega_edit_title: "Edit task",
    entrega_edit_submit: "Edit",
    historia_list_title: "Requirements",
    historia_list_add: "Create requirement",
    historia_add_title: "Add requirement",
    historia_id_entrega: "Task id:",
    historia_id_historia: "Requirement id:",
    historia_texto: "Text requirement:",
    historia_add_submit: "Add",
    historia_edit_title: "Edit requirement",
    historia_edit_submit: "Edit",
    historia_select_task: "Select task...",
    link_home: "Home",
    link_user: "Users",
    link_task: "Tasks",
    link_requirements: "Requirements",
    link_logout: "Log out",
    link_login: "Log in",
    link_register: "Registration",
    link_language: "Languages",
    link_edit: "Edit",
    user_search_title: "Search user",
    user_search_submit: "Search",
    user_search_button: "Search user",
    entrega_l_search: "Search task",
    entrega_search_title: "Search task",
    entrega_search_submit: "Search",
    historia_search_title: "Search requirement",
    historia_list_search: "Search requirement",
    historia_search_submit: "Search",
    historia_add_title: "Create requirement",
    entrega_delete_confirm: "Delete task?",
    user_delete_confirm: "Delete user?",
    historia_delete_confirm: "Delete requirement?",
    error_entrega_desdehasta: "Date 'from' later than date 'to'",

    login_success: "Successful login.",

    error_permission_denied: "permission denied",
    error_invalid_json: "invalid JSON sent in request",
    error_keys_missing: "keys missing in JSON",
    error_bad_request_method: "invalid request code",
    error_user_not_found: "user not found",
    error_password_match: "wrong password entered",
    error_user_exists: "user already exists",
    error_no_get_element: "couldn't find requested object",
    error_more_get_element: "more than one object that fits found",
    error_insert: "could not insert object",
    error_insert_exists: "object to insert already exists",
    error_no_delete_element: "couldn't find object to delete",
    error_delete: "couldn't delete object",
    error_no_put_element: "couldn't find object to modify",
    error_update: "couldn't modify object",
    error_task_hasreqs: "task has requirements available",
    error_task_notfound: "task not found",
    error_auth_fail: "user authentication failed",
    error_generated_eval: "assessments for the task have already been generated",

    error_usuarios_login: "field Login can contain letters and numbers only",
    error_usuarios_dni: "field DNI must contain eight digits and one letter",
    error_usuarios_email: "field Email must be a valid email address (x@y.z)",
    error_entregas_id: "field Id can contain letters and digits only",
    error_entregas_nombre: "field Name must not be empty",
    error_entregas_date: "inserted date not of format year-month-day",
    error_historia_identrega: "field Task Id can contain only letters and digits",
    error_historia_idhistoria: "field Requirement Id must contain a number",
    error_has_assessments: "submission selected already has assessments",

    entregausuario_list_title: "User Submissions",
    entregausuario_l_add: "Add submission",
    entregausuario_l_search: "Search submission",
    entregausuario_l_login: "User Id",
    entregausuario_l_identrega: "Task Id",
    entregausuario_l_alias: "Alias",
    entregausuario_l_horas: "Hours",
    entregausuario_l_link: "Link to file",
    entregausuario_link: "Link...",
    link_submissions: "Submissions",

    entregausuario_add_title: "Add submission",
    entregausuario_identrega: "Task:",
    entregausuario_horas: "Hours:",
    entregausuario_alias: "File alias:",
    entregausuario_ruta: "File route:",
    entregausuario_file: "File:",
    entregausuario_add_submit: "Submit",
    entregausuario_delete_confirm: "Delete user submission?",

    entregausuario_search_title: "Search submissions",
    entregausuario_login: "User name:",
    entregausuario_search_submit: "Search",

    entregausuario_edit_title: "Edit user submission",
    entregausuario_edit_submit: "Edit",

    link_assessments: "Assessments",
    evaluaciones_list_title: "List of assessments",
    evaluaciones_l_identrega: "Task Id",
    evaluaciones_l_aliasautor: "Author",
    evaluaciones_l_loginEvaluador: "Assesser",
    generate_eval: "Generate Assessment",

    link_results: "Grades",

    resultados_list_title: "Evaluation list",
    resultados_l_identrega: "Task Id",
    resultados_l_aliasautor: "Author",
    resultados_l_loginEvaluador: "Assesser",
    resultados_l_idhistoria: "Req. Id",
    resultados_l_correccion: "Grade",
    resultados_l_comentario: "Comment",
    resultados_l_add: "Add grade",

    resultados_delete_confirm: "¿Delete grade?",

    resultados_add_title: "Add grade",
    resultados_evaluacion: "Assessment:",
    resultados_idhistoria: "Id Requirement:",
    resultados_correccion: "Grade:",
    resultados_comentario: "Comments:",
    resultados_add_submit: "Submit",

    resultados_identrega: "Task Id:",
    resultados_aliasautor: "Author:",
    resultados_loginEvaluador: "Assesser:",

    resultados_search_title: "Search grades",
    resultados_search_submit: "Search",
    resultados_l_search: "Search grades",
    resultados_search_title: "Search grades",

    evaluacion_add_title: "Add assessment",
    evaluacion_entrega: "Submission:",
    evaluacion_loginEvaluador: "Assesser:",
    evaluacion_add_submit: "Add",
    evaluaciones_add: "Add assessment",

    evaluacion_search_title: "Search assessment",
    evaluacion_alias: "Submission alias:",
    evaluacion_search_submit: "Search",
    evaluaciones_search: "Search assessment",

    error_submission_date_passed: "submission date already passed",

    generate_result: "Grade",
    resultados_eval_by: "Graded by:",
    test: ""
};