var _lang = {
    lang_name: "Español",
    login_title: "Login",
    login_user_name: "Nombre de usuario:",
    login_password: "Contraseña:",
    login_button: "Conectar",
    register_title: "Registro",
    register_login: "Nombre de usuario:",
    register_password: "Contraseña:",
    register_name: "Nombre:",
    register_surname: "Apellidos:",
    register_id: "DNI:",
    register_email: "Correo:",
    register_button: "Registro",
    user_title: "Usuarios",
    user_login: "Usuario",
    user_name: "Nombre",
    user_surname: "Apellidos",
    user_email: "Correo",
    user_add_button: "Añadir",
    modify_button: "Editar",
    user_add_title: "Añadir usuario",
    user_add_login: "Login:",
    user_add_password: "Contraseña:",
    user_add_id: "DNI:",
    user_add_submit: "Enviar",
    user_edit_title: "Modificar usuario",
    user_edit_submit: "Modificar",
    entrega_add_title: "Añadir entrega",
    entrega_id: "Id:",
    entrega_name: "Nombre:",
    entrega_from: "Desde:",
    entrega_to: "Hasta:",
    entrega_to_corr: "Corrección hasta:",
    entrega_add_submit: "Añadir",
    entrega_list_title: "Lista de entregas",
    entrega_l_id: "Id",
    entrega_l_name: "Nombre",
    entrega_l_from: "Desde",
    entrega_l_to: "Hasta",
    entrega_l_to_corr: "Corrección",
    entrega_l_add: "Añadir entrega",
    entrega_edit_title: "Editar entrega",
    entrega_edit_submit: "Modificar",
    historia_list_title: "Historias",
    historia_list_add: "Crear historia",
    historia_add_title: "Añadir historia",
    historia_id_entrega: "Id de entrega:",
    historia_id_historia: "Id Historia:",
    historia_texto: "Texto historia:",
    historia_add_title: "Añadir historia",
    historia_add_submit: "Añadir",
    historia_edit_title: "Modificar historia",
    historia_edit_submit: "Modificar",
    historia_select_task: "Elija tarea...",
    link_home: "Principal",
    link_user: "Usuarios",
    link_task: "Entregas",
    link_requirements: "Historias",
    link_logout: "Salir",
    link_login: "Login",
    link_register: "Registro",
    link_language: "Idiomas",
    link_edit: "Modificar",
    user_search_title: "Buscar usuario",
    user_search_submit: "Buscar",
    user_search_button: "Buscar usuario",
    entrega_l_search: "Buscar entrega",
    entrega_search_title: "Buscar entrega",
    entrega_search_submit: "Buscar",
    historia_search_title: "Buscar historia",
    historia_list_search: "Buscar historia",
    historia_search_submit: "Buscar",
    entrega_delete_confirm: "¿Borrar entrega?",
    user_delete_confirm: "¿Borrar usuario?",
    historia_delete_confirm: "¿Borrar historia?",
    error_entrega_desdehasta: "Fecha de inicio más tardía que fecha de fin",
    
    login_success: "Login correcto.",

    error_permission_denied: "permiso denegado",
    error_invalid_json: "JSON inválido en petición",
    error_keys_missing: "faltan claves en JSON",
    error_bad_request_method: "método de petición inválido",
    error_user_not_found: "usuario no encontrado",
    error_password_match: "contraseña incorrecta",
    error_user_exists: "el usuario ya existe",
    error_no_get_element: "no se ha encontrado el objeto",
    error_more_get_element: "más de un objeto encontrado que encaja",
    error_insert: "no se pudo insertar objeto",
    error_insert_exists: "el objeto a insertar ya existe",
    error_no_delete_element: "no se pudo encontrar objeto para borrar",
    error_delete: "no se pudo borrar el objeto",
    error_no_put_element: "no se pudo encontrar el objeto a modificar",
    error_update: "no se pudo modificar el objeto",
    error_task_hasreqs: "la entrega tiene historias disponibles",
    error_task_notfound: "entrega no encontrada",
    error_auth_fail: "la autenticación del usuario falló",
    error_generated_eval: "las evaluaciones para la entrega ya se han generado",

    error_usuarios_login: "campo Login sólo puede contener letras y números",
    error_usuarios_dni: "campo DNI debe contener 8 dígitos y una letra",
    error_usuarios_email: "campo Email debe ser una dirección de correo válida (x@y.z)",
    error_entregas_id: "campo Id sólo puede contener letras y números",
    error_entregas_nombre: "campo Nombre no puede estar vacío",
    error_entregas_date: "fecha no tiene formato año-mes-día",
    error_historia_identrega: "campo Id de Entrega sólo puede contener letras y números",
    error_historia_idhistoria: "campo Id Historia debe contener un número",
    error_has_assessments: "entrega seleccionada ya tiene evaluaciones",

    entregausuario_list_title: "Entregas de Usuario",
    entregausuario_l_add: "Añadir entrega",
    entregausuario_l_search: "Buscar entrega",
    entregausuario_l_login: "Id Usuario",
    entregausuario_l_identrega: "Id Entrega",
    entregausuario_l_alias: "Alias",
    entregausuario_l_horas: "Horas",
    entregausuario_l_link: "Enlace",
    entregausuario_link: "Enlace...",
    link_submissions: "Entregas Usuario",

    entregausuario_add_title: "Añadir entrega",
    entregausuario_identrega: "Entrega:",
    entregausuario_horas: "Horas empleadas:",
    entregausuario_alias: "Alias fichero:",
    entregausuario_ruta: "Ruta fichero:",
    entregausuario_file: "Fichero:",
    entregausuario_add_submit: "Entregar",
    
    entregausuario_search_title: "Buscar entregas de usuario",
    entregausuario_login: "Nombre usuario:",
    entregausuario_search_submit: "Buscar",
    entregausuario_delete_confirm: "¿Desea borrar la entrega?",

    entregausuario_edit_title: "Modificar entrega de usuario",
    entregausuario_edit_submit: "Modificar",

    link_assessments: "Evaluaciones",
    evaluaciones_list_title: "Lista evaluaciones",
    evaluaciones_l_identrega: "Id Entrega",
    evaluaciones_l_aliasautor: "Autor",
    evaluaciones_l_loginEvaluador: "Evaluador",
    generate_eval: "Generar Evaluación",

    link_results: "Resultados",

    resultados_list_title: "Lista de resultados",
    resultados_l_identrega: "Id Entrega",
    resultados_l_aliasautor: "Autor",
    resultados_l_loginEvaluador: "Evaluador",
    resultados_l_idhistoria: "Id Historia",
    resultados_l_correccion: "Corrección",
    resultados_l_comentario: "Comentario",
    resultados_l_add: "Añadir resultado",

    resultados_delete_confirm: "¿Desea eliminar la evaluación?",

    resultados_add_title: "Añadir resultado",
    resultados_evaluacion: "Evaluación:",
    resultados_idhistoria: "Id Historia:",
    resultados_correccion: "Nota:",
    resultados_comentario: "Comentarios:",
    resultados_add_submit: "Enviar",

    resultados_identrega: "Id Entrega:",
    resultados_aliasautor: "Autor:",
    resultados_loginEvaluador: "Evaluador:",
    
    resultados_search_title: "Búsqueda de resultados",
    resultados_search_submit: "Buscar",
    resultados_l_search: "Búsqueda",
    resultados_search_title: "Búsqueda de resultados",

    evaluacion_add_title: "Añadir evaluación",
    evaluacion_entrega: "Entrega:",
    evaluacion_loginEvaluador: "Evaluador:",
    evaluacion_add_submit: "Añadir",
    evaluaciones_add: "Añadir evaluación",

    evaluacion_search_title: "Buscar evaluación",
    evaluacion_alias: "Alias entrega:",
    evaluacion_search_submit: "Buscar",
    evaluaciones_search: "Buscar evaluación",
    error_submission_date_passed: "fecha de envío de entrega ya pasó",

    generate_result: "Corregir",

    resultados_eval_by: "Evaluado por:",

    test: ""
};